### PR TITLE
Update data structures

### PR DESCRIPTION
**Pull request by Leonhard-B**
Solution to issue #206 (Old data structures waste memory space)
All DataFrames in pyomo_model_prep() in input.py changed to dictionaries. Removed all doubly occuring entries ("DataFrames") in pyomo_model_prep() and changed model.py for compatibility. Memory usage does not decrease, but runtime is slightly better.

### CODE REVIEW

**Comment by KSchoenleber** [comment]
Thank you for the nice pull request. I have a few comments:

1. m.sit_area can indeed be completely erased (input.py line 120)
2. In the try...except in model.py the exception seems to be the rule. If so please replace with if statement
3. Are all files pep8 conform? (Does not seem to be the case for inline comments)

**Comment by KSchoenleber** [comment]
Thank you for the update that resolves all my earlier points. One small thing though. Could you reset GLPK as standard in runme.py.

**Comment by maledo** [comment]
As there were merge conflicts with master, I had to resolve them.

Unfortunately, while the "cost" optimization runs, the "CO2" optimization does not work anymore. I've obviously missed something. Please resolve.

**Comment by maledo** [comment]
Thank you for fixing it. I will merge.

**Pull request merged**
