### PR TITLE
Functionality for optional name for plot or report added (fix #180)

### LINKED ISSUE #180: Renaming by multiple sites per report/plot
At the moment, multiple sites per report/plot lead to a string concatenation of the various sites for the title and the file name. In case of e.g. 10 sites this leads to a ridiculous long name which sometimes cannot even be opened by the image viewer.

It would be helpful, if a self defined name can be given instead.

### PR DESCRIPTION
**Pull request by lodersky**
* plot.py: def result_figures: added plot_tuples names and changed construction of title and name of plot
* report.py: def report: added report_tuples_names, changed construction of report sheets and names
* runme.py def run_scenario: added plot_tuples_names and plot_tuples_names
* pep8 for all files checked

### CODE REVIEW

**Comment by KSchoenleber** [comment]
This is a very nice improvement to the functionality. It would probably be very helpful if the changes were added into the documentation as well. This can, however, happen in another pull request.

**Comment by KSchoenleber** [comment]
I tried to test the feature but I was not sure how to put in the names. Please add at least an example and I thin the doc is essential in this case!

**Comment by lodersky** [comment]
Added examples to the documentation. I hope, it is clearer now.

**Comment by KSchoenleber** [comment]
The added doc is quite helpful. I get, however, a syntax error when running your version (cloned directly from your repository on branch 'optional-name-plot-report'. I assume this is the branch to be merged, right?). The relevant part of the error message reads:

urbs/urbs/report.py", line 84
    timeseries[(report_tuples_names[sit], com)] =

Could you please check what the problem is.

**Comment by lodersky** [comment]
I fixed the error. It should work now. 
And yes, it is on branch 'optional-name-plot-report'.

**Pull request merged**
