### PR TITLE
Efficiency variation factors added

### PR DESCRIPTION
**Pull request by KSchoenleber**
A new feature for, e.g., the improved modeling of heat systems or the incorporation of known maintenance intevals:

- A new worksheet in the input sheet 'TimeVarEff' created
- In the new input sheet time series for (site, process)-tuples are given that are multiplied to the output ratio of  all commodities for the process
- Environmental commodities are exempt from the multiplication since they are typically linked to inputs, as, e.g., CO2 emissions are linked to the fossil input.

Backwards compatibility with older input files is assured
The feature is tested.

This solves issue #189

### CODE REVIEW

**Comment by maledo** [comment]
Interesting feature. I have to test it!

**Comment by maledo** [comment]
Shall we create issues for the solved problems at hand? It would probably be beneficial for the workflow...
What do you think?

**Comment by KSchoenleber** [comment]
I think that is fine. I will do that

**Comment by sonercandas** [comment]
Did you check how the output commodities are calculated when a process has both partial load and variable efficiency features? I think the sets for these constraints are not defined in a mutually exclusive way

**Comment by KSchoenleber** [comment]
Good point! That is definately something I have to fix. It will require I think a third case, where both features are active.

**Comment by maledo** [comment]
Have your students/colleagues already worked with the feature?

**Comment by KSchoenleber** [comment]
I fixed Soners point. The set definitions should now be correct in all 4 cases (no feature, only partial, only timevar, partial and timevar).

**Comment by KSchoenleber** [comment]
No colleague has worked with it so far. As possible names:

- VarOut
- TimeVarOut
- TimeVar
- VarEff
- TimeVarEff

**Comment by KSchoenleber** [comment]
All discussed comments are now implemented. The worksheet is now renamed to "TimeVarEff".
The branch was tested on various systems (Simius, Ingas System, Spyder on Sisis System) and works without problems.

**Comment by maledo** [comment]
Thanks for the updates! I will merge.

**Pull request merged**
