### PR TITLE
Modular urbs

### PR DESCRIPTION
**Pull request by froehlie**
Optionale Features: 
Intertemporal (functionality from Campus version)
Transmission
Storage
DSM
Buy Sell Price
Time Variable Efficiency
Expansion (capacities as Pyomo expression)

Kürzlich noch verändert (seit letztem Treffen, wie in E-Mail beschrieben):
- default year für backwards compatibility
- Expansion jetzt für alle Tuple die in den installierten Tupeln sowie in den const_cap tupeln enthalten sind (die const_cap Tupel können nur den ersten stf haben, d.h. die Frage Param oder Var kann nun nicht mehr unterschiedlich für einzelne Stützjahre unterschieden werden)
- In allen output files (output.py, plot.py, report.py) finden sich keine Modusabfragen mehr. Um die Funktionalität trotzdem zu gewährleisten habe ich in get_entity eine try: ... except AttributeError: return empty series Routine eingefügt.
- Alle scenarios sollten funktionieren, auch für meinen intertemporalen Beispiel Input basierend auf dem mimo-example 

Eine Bitte: Könnte ich nach dem Testen die timelog.txt Dateien aus dem results Ordner bekommen, zusammen mit den relevanten Optionen (Zeitschritte, größe des problems, Solver etc.). Optimal wäre natürlich noch der Vergleich mit dem master

### CODE REVIEW

**Comment by kevinmilis** [comment]
I encountered two types of warnings when running runme.py, using the provided excel input files (2019.xlsx, 2024.xlsx, 2029.xlsx, 2034.xlsx):

*  `input.py:157: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version of pandas will change to not sort by default` (repeats for lines 157, 161 & 162 of input.py).
* `input.py:211: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  pro_const_cap = pro_const_cap[process['inst-cap'] == process['cap-lo']]` (repeats for lines 211, 231, 239 & 241 of input.py).

Does it make sense to already fix them beforehand?

**Comment by sonercandas** [comment]
> I encountered two types of warnings when running runme.py, using the provided excel input files (2019.xlsx, 2024.xlsx, 2029.xlsx, 2034.xlsx):
> 
> * `input.py:157: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version of pandas will change to not sort by default` (repeats for lines 157, 161 & 162 of input.py).
> * `input.py:211: UserWarning: Boolean Series key will be reindexed to match DataFrame index. pro_const_cap = pro_const_cap[process['inst-cap'] == process['cap-lo']]` (repeats for lines 211, 231, 239 & 241 of input.py).
> 
> Does it make sense to already fix them beforehand?

**First warning:**
When the data for process, transmission and storage are concatenated over each support time year, there is a mismatch between the number of columns. This is because the first support time year has the additionals columns such as inst-cap, while the others do not. When there is this misalignment of columns, pandas apparently sorts the columns alphabeitically by default. You can disable this sorting by modifying the concatenation lines as follows:

`process = pd.concat(pro,sort=False)`
`storage = pd.concat(sto,sort=False)`
`transmission = pd.concat(tra,sort=False)`

**Second warning:**
Here, when defining the "no-expansion" dataframes for processes/transmissions/storages: I think the second query of `inst-cap == cap-lo` is obsolete. So if you remove these lines:

`pro_const_cap = pro_const_cap[process['inst-cap'] == process['cap-lo']]`
`        tra_const_cap = tra_const_cap[` 
`             transmission['inst-cap'] == transmission['cap-lo']]`
`        sto_const_cap_c = sto_const_cap_c[` 
`             storage['inst-cap-c'] == storage['cap-lo-c']]` 
`         sto_const_cap_p = sto_const_cap_p[` 
`            storage['inst-cap-p'] == storage['cap-lo-p']]`
the warning disappears without any loss in functionality.

**Comment by KSchoenleber** [comment]
I am now testing the code as well. I found the following problems:

* The warning mentioned above creates an error when the obsolete query returns false while the first returns true. => Please remove the obsolete second query
* There are additional warnings for all inst-tuples in the intertemporal model. This should be written differently so that these warnings disappear
* more later

Furthermore there is a little tidying up to do:

* A lot of old lines in runme.py are just commented out and should be removed.
* The timing log should also be removed (after the testing phase where it might be useful)

**Comment by kevinmilis** [comment]
I am encountering an error when I try and run a model for just one year: the LP is formulated and solved, the output xlsx is generated as well, but the graphs are not made. Instead the following error is reported:

*  `report.py:line 41: in report for stf, sit, com in report_tuples: ValueError: not enough values to unpack (expected 3, got 2)`

**Comment by froehlie** [comment]
Did you assign he plot and report tuples in the runme.py file correctly? They need to be (year,'site','commodity') tuples for one year models as well. I left the plot and report tuples for the mimo-example as a comment, you can look it up there.

**Comment by KSchoenleber** [comment]
I have now tested the feature a little more extensively with a new made input file. Overall everything seems to work well. Thank you for the excellent work!

I only noted one small things that might be good to change:

If there are no values in time series in Buy/Sell, the mode is still on. This could potentially lead to problems. My suggestion is to change or at least amend the query for the mode 'bsp' in 'identify.py' by a scan of the index of data['commodity'] for the types 'Buy' or 'Sell' to avoid this false positive.

Aditional points are:
- Please make all files pep8 conform. You can find the non-conform parts by typing 'pep8 filename.py' in the command prompt in the folder of the file in question.
- Update validation.py
- Some general cleaning work, i.e. chakcing if lines currently commented out can be erased entirely

**Comment by maledo** [comment]
Looking at the current status quo, I don't like all the commented lines in the runme file. Should they be there, or not? Having so much unused code in there is not suitable for a release candidate.

**Comment by maledo** [comment]
Running tests:

I cloned the current status of @froehlie and just let it run, and I get a ValueError:

> ValueError: Ensure cap_lo <= cap_up and inst_cap <= cap_up for all processes.

Additionally, I get `FutureWarnings` from pandas concerning the `pd.concat` lines:

> FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.
>To accept the future behavior, pass 'sort=False'.
> To retain the current behavior and silence the warning, pass 'sort=True'.

My settings:
* Python 3.6
* Pandas 0.23.4

**Comment by maledo** [comment]
My testing continues. If I try to let it run with one of my own input files, as far as I know, it sets a supportimeframe. In [validation.py Line 111](https://github.com/froehlie/urbs/blob/621cd943ca44a61bfcc28d4a694d9e10fa74fdfb/urbs/validation.py#L111), the sites are checked via the commodity sheet. If you take `level[0]` of the commodity index, it results in the supporttimeframe instead of the sites. Therefore, I get an unnecessary error.

**Comment by maledo** [comment]
If I screw validation and let it run with my own input file, I end up in a error in plot:
> ValueError: operands could not be broadcast together with shapes (168,) (169,) 
Do you know something about that as well, @froehlie ?

**Comment by froehlie** [comment]
I think I've seen this error before but I can't remember when. Probably it also has to do with the plot tuples.

**Pull request merged**
