### PR TITLE
Standard run repair

### LINKED ISSUE #209: LP HAS NO PRIMAL FEASIBLE SOLUTION for scenario_co2_tax_mid
It seems like the programm is unable to solve the model of the scenario_co2_tax_mid. Depending of the version of matlotlib this is either handled by plotting empty graphs or by throwing an exception. In the first case the programm finishes normally, except for telling LP HAS NO PRIMAL FEASIBLE SOLUTION if tee is set True. The graphs are empty except for the demand curve.
The funny thing is, that the newer version of matplotlib is throwing the exception and the older one is capable of handling the results (by not doing the plotting).
[output scenario_co2_tax_mid.txt](https://github.com/tum-ens/urbs/files/2589416/output.scenario_co2_tax_mid.txt)

### PR DESCRIPTION
**Pull request by KSchoenleber**
In the case of CO2 optimization the standard scenarios were not feasible. The reason for this is the missing "Slack process" for CO2 optimization (no costs, extremely high emissions). This can not be part of the standard input file, since it would compromise the normal operation.

This resolves #209

### CODE REVIEW

**Comment by sonercandas** [comment]
I think this can be merged

**Comment by maledo** [comment]
As the Diff is not working on the xlsx file, can you please include the changes next time in the commit message? E.g. which value you changed, otherwise it is not easily understandable (especially in the future), which parameter caused the issue.

**Comment by KSchoenleber** [comment]
That is true. So here comes the requested clarification:

In the file mimo-example.xlsx, in worksheet global the 'Cost limit' was increased to  35 bn.

**Comment by maledo** [comment]
Thank you. My tests were successful, I will merge.

**Pull request merged**
